Move sanity check logic from rc.asd to anything-sync-daemon Make the sanity check systematic

diff --git a/anything-sync-daemon b/anything-sync-daemon
--- a/anything-sync-daemon
+++ b/anything-sync-daemon
@@ -3,6 +3,19 @@
 # By graysky <graysky AT archlinux DOT us>
 # Inspired by some code originally  written by Colin Verot
 
+sanity() {
+	# check the configuration
+	if [[ -z "${WHATTOSYNC[0]}" ]]; then
+		echo "Must define at least one directory in $CONF" >&2
+		return 2
+	fi
+
+	if [[ ! -d "$TMPFS" ]]; then
+		echo "I cannot read $TMPFS which is defined in $CONF" >&2
+		return 3
+	fi
+}
+
 sync() {
 	# sync hdd to tmpfs and back again
 	local i STATIC LINK
@@ -71,7 +84,7 @@ done
 shift "$((${OPTIND} - 1))"
 
 [[ ! -f "$CONF" ]] && {
-	echo "$CONF does not exist!"
+	echo "$CONF does not exist!" >&2
 	exit 1
 }
 
@@ -79,20 +92,25 @@ source "$CONF"
 
 declare -r VOLATILE="$TMPFS/asd"
 
+
 case "$1" in
+	sanity)
+		sanity;;
 	check)
+		sanity || exit $?
 		# do not run if the daemon is running
 		[[ ! -f /run/daemons/asd ]] && check
 		;;
 	sync)
+		sanity || exit $?
 		sync
 		;;
 	unsync)
+		sanity || exit $?
 		# make sure the daemon is running
 		[[ -f /run/daemons/asd ]] && unsync
 		;;
 	*)
 		# keep user from messing with this directly
-		echo "You should not call this script directly, let the /etc/rc.d/asd do it for you!" && exit 0
+		echo "You should not call this script directly, let the /etc/rc.d/asd do it for you!" >&2 && exit 0
 esac
-exit 0
