more verbose output when overlay module is not loaded

diff --git a/common/anything-sync-daemon.in b/common/anything-sync-daemon.in
--- a/common/anything-sync-daemon.in
+++ b/common/anything-sync-daemon.in
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Anything-sync-deamon by graysky <graysky AT archlinux DOT us>
+# Anything-sync-daemon by graysky <graysky AT archlinux DOT us>
 # Inspired by some code originally written by Colin Verot
 #
 
@@ -48,9 +48,12 @@ dep_check() {
 	command -v awk >/dev/null 2>&1 || {
 	echo "I require awk but it's not installed. Aborting." >&2; exit 1; }
   if [[ $OLFS -eq 1 ]]; then
-    modprobe overlay &>/dev/null || { 
-    echo -e " ${BLD}Overlayfs requires linux kernel >= 3.18."
-    echo -e " ${BLD}Please modprobe overlay and try again if running a supported kernel. ${RED}Aborting!"${NRM} >&2; exit 1;}
+    modprobe overlay &>/dev/null || {
+    youare=$(logname)
+    echo -e " ${BLD}The overlay module needs to be loaded to use psd in overlayfs mode."${NRM}
+    echo -e " ${BLD}User $youare does not have permission to run: ${BLU}$(which modprobe) overlay${NRM}${BLD}"
+    echo -e " ${BLD}Load it manually and try again or remove the option from ${BLU}$ASDCONF${NRM}${BLD}."${NRM}
+    echo -e " ${BLD}Note that a kernel version >=3.18.0 is required for overlayfs mode. ${RED}Aborting!"${NRM} >&2; exit 1;}
   fi
 }
 
