add flock to avoid simultaneous syncs
flock will now be a dependency of asd, asd will automatically lock
itself whenever run so that at a point of time, only one instance of asd
can be run. This can avoid race conditions that causes the rsyncs to
lockup due to multiple parallel syncs happening

diff --git a/common/anything-sync-daemon.in b/common/anything-sync-daemon.in
--- a/common/anything-sync-daemon.in
+++ b/common/anything-sync-daemon.in
@@ -13,6 +13,13 @@ debug() {
   fi
 }
 
+debug "checking flock"
+  command -v flock >/dev/null 2>&1 || {
+  echo "I require flock but it's not installed. Aborting." >&2
+  exit 1; }
+debug "flock found, waiting for lock"
+[[ ${FLOCKER} != "$0" ]] && exec env FLOCKER="$0" flock -e "$0" "$0" "$*" ||
+
 BLD="\e[01m"
 RED="\e[01;31m"
 GRN="\e[01;32m"
